### ISSUE TITLE
HTML class not found in Alert.php

### ISSUE THREAD

**Issue by nzomedia** [caouecs/Laravel-Bootstrap3#5]
I've just installed laravel-bootstrap3 on a laravel5.3 project with laravelCollective/html.
I failed to use the Alert facade it causes a class not found error related to "HTML" class at line 72 of Alert.php file. The solution was to rewrite the class name from HTML to Html at line 72 and at the beguining of the script "use HTML" -> "use Html". It works now

I think this is due to the fact that laravelcollective/Html uses an alias named Html rather than HTML.

**Comment by caouecs** [comment]
Hi,
can you do a pull request ?

**Comment by nzomedia** [comment]
Hi, i've juste made the pull request. I'm sorry i haven't seen your comment earlyer.

**Comment by caouecs** [comment]
Thanks
